name: "Simple Aligenie Skill Server"
description: "一个简易天猫精灵技能服务后端，基于NodeJS"
version: "1.0.0"
slug: "simple_aligenie_skill_server"
url: https://github.com/hassio-addons/
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
map:
  - config
  - ssl
  - addons
  - backup
  - share
  - media
  - data
options:
  certificates:
    - certificate_file_name: "认证文件名.txt"
      certificate_file_content: "认证文件内容"
  intents:
    - intent_name: '意图标识'
      webhook_id: '该意图发送给 homeassistant 的 webhook id'
      reply: '天猫精灵回复的文案'
  ha_url_with_port: 'http(s)://[外网可访问的homeassitant地址]:[端口]'
  route: '天猫精灵服务器发送请求的路由'
  port: 20255
schema:
  certificates:
    - certificate_file_name: "str"
      certificate_file_content: "str"
  intents:
    - intent_name: "str"
      webhook_id: "str"
      reply: "str"
  ha_url_with_port: "str"
  route: "str"
  port: port
ports:
  20255/tcp: 20255
ports_description:
  20255/tcp: "尽量不要改。如需修改，和配置中的 port 保持一致。"
